# Generated by Django 4.0.1 on 2023-08-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_runner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spider',
            name='spider_class',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spider',
            name='spider_file',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
