# Generated by Django 4.0.1 on 2023-08-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_runner', '0002_spider_spider_class_spider_spider_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpiderExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spider_name', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
